// Simple BIP39 wordlist (2048 words) - using the standard English wordlist
const WORDLIST = [
  'abandon', 'ability', 'able', 'about', 'above', 'absent', 'absorb', 'abstract', 'absurd', 'abuse',
  'access', 'accident', 'account', 'accuse', 'achieve', 'acid', 'acoustic', 'acquire', 'across', 'act',
  'action', 'actor', 'actress', 'actual', 'adapt', 'add', 'addict', 'address', 'adjust', 'admit',
  'adult', 'advance', 'advice', 'aerobic', 'affair', 'afford', 'afraid', 'again', 'age', 'agent',
  'agree', 'ahead', 'aim', 'air', 'airport', 'aisle', 'alarm', 'album', 'alcohol', 'alert',
  'alien', 'align', 'all', 'alley', 'allow', 'almost', 'alone', 'alpha', 'already', 'also',
  'alter', 'always', 'amateur', 'amazing', 'among', 'amount', 'amused', 'analyst', 'anchor', 'ancient',
  'anger', 'angle', 'angry', 'animal', 'ankle', 'announce', 'annual', 'another', 'answer', 'antenna',
  'antique', 'anxiety', 'any', 'apart', 'apology', 'appear', 'apple', 'approve', 'april', 'arch',
  'arctic', 'area', 'arena', 'argue', 'arm', 'armed', 'armor', 'army', 'around', 'arrange',
  'arrest', 'arrive', 'arrow', 'art', 'artist', 'artwork', 'ask', 'aspect', 'assault', 'asset',
  'assist', 'assume', 'asthma', 'athlete', 'atom', 'attack', 'attend', 'attitude', 'attract', 'auction',
  'audit', 'august', 'aunt', 'author', 'auto', 'autumn', 'average', 'avocado', 'avoid', 'awake',
  'aware', 'away', 'awesome', 'awful', 'awkward', 'axis', 'baby', 'bachelor', 'bacon', 'badge',
  'bag', 'balance', 'balcony', 'ball', 'bamboo', 'banana', 'banner', 'bar', 'barely', 'bargain',
  'barrel', 'base', 'basic', 'basket', 'battle', 'beach', 'bean', 'beauty', 'because', 'become',
  'beef', 'before', 'begin', 'behave', 'behind', 'believe', 'below', 'belt', 'bench', 'benefit',
  'best', 'betray', 'better', 'between', 'beyond', 'bicycle', 'bid', 'bike', 'bind', 'biology',
  'bird', 'birth', 'bitter', 'black', 'blade', 'blame', 'blanket', 'blast', 'bleak', 'bless',
  'blind', 'blood', 'blossom', 'blouse', 'blue', 'blur', 'blush', 'board', 'boat', 'body',
  'boil', 'bomb', 'bone', 'bonus', 'book', 'boost', 'border', 'boring', 'borrow', 'boss',
  'bottom', 'bounce', 'box', 'boy', 'bracket', 'brain', 'brand', 'brass', 'brave', 'bread',
  'breeze', 'brick', 'bridge', 'brief', 'bright', 'bring', 'brisk', 'broccoli', 'broken', 'bronze',
  'broom', 'brother', 'brown', 'brush', 'bubble', 'buddy', 'budget', 'buffalo', 'build', 'bulb',
  'bulk', 'bullet', 'bundle', 'bunker', 'burden', 'burger', 'burst', 'bus', 'business', 'busy',
  'butter', 'buyer', 'buzz', 'cabbage', 'cabin', 'cable', 'cactus', 'cage', 'cake', 'call',
  'calm', 'camera', 'camp', 'can', 'canal', 'cancel', 'candy', 'cannon', 'canoe', 'canvas',
  'canyon', 'capable', 'capital', 'captain', 'car', 'carbon', 'card', 'care', 'careful', 'carry',
  'cart', 'case', 'cash', 'casino', 'castle', 'casual', 'cat', 'catalog', 'catch', 'category',
  'cattle', 'caught', 'cause', 'caution', 'cave', 'ceiling', 'cell', 'cement', 'census', 'center',
  'central', 'century', 'cereal', 'certain', 'chain', 'chair', 'chalk', 'champion', 'change', 'chaos',
  'chapter', 'charge', 'chase', 'cheap', 'check', 'cheese', 'chef', 'cherry', 'chest', 'chicken',
  'chief', 'child', 'chimney', 'choice', 'choose', 'chronic', 'chuckle', 'chunk', 'churn', 'cigar',
  'cinnamon', 'circle', 'citizen', 'city', 'civil', 'claim', 'clap', 'clarify', 'claw', 'clay',
  'clean', 'clerk', 'clever', 'click', 'client', 'cliff', 'climb', 'clinic', 'clip', 'clock',
  'clog', 'close', 'cloth', 'cloud', 'clown', 'club', 'clump', 'coach', 'coal', 'coast',
  'coat', 'coffee', 'coil', 'coin', 'cold', 'collar', 'collect', 'color', 'column', 'combine',
  'come', 'comfort', 'comic', 'common', 'company', 'concert', 'conduct', 'confirm', 'connect', 'consensus',
  'consider', 'constant', 'construct', 'control', 'convince', 'cook', 'cool', 'cope', 'copy', 'core',
  'corn', 'correct', 'cost', 'cotton', 'couch', 'country', 'couple', 'course', 'cousin', 'cover',
  'coyote', 'crack', 'cradle', 'craft', 'cram', 'crane', 'crash', 'crawl', 'crazy', 'cream',
  'credit', 'cricket', 'crime', 'crisp', 'critic', 'crop', 'cross', 'crowd', 'crown', 'crucial',
  'cruel', 'crush', 'crystal', 'cub', 'cuisine', 'culture', 'cupboard', 'curious', 'current', 'curtain',
  'curve', 'cushion', 'custom', 'cute', 'cycle', 'dad', 'damage', 'damp', 'dance', 'danger',
  'dare', 'darkness', 'daughter', 'dawn', 'day', 'deal', 'debate', 'debris', 'decade', 'decide',
  'decline', 'decorate', 'decrease', 'deer', 'defense', 'define', 'defy', 'degree', 'delay', 'deliver',
  'demand', 'dense', 'density', 'deny', 'department', 'depend', 'deposit', 'depth', 'deput', 'deputy',
  'derive', 'describe', 'desert', 'design', 'desk', 'despair', 'destroy', 'detail', 'detect', 'develop',
  'device', 'devote', 'diagram', 'dial', 'diamond', 'diary', 'dice', 'diet', 'differ', 'digital',
  'dignity', 'dilemma', 'dinner', 'dinosaur', 'direct', 'dirt', 'disagree', 'discover', 'disease', 'dish',
  'dismiss', 'disorder', 'display', 'distance', 'divert', 'divide', 'divorce', 'doctor', 'document', 'dog',
  'doll', 'dolphin', 'domain', 'donate', 'donkey', 'donor', 'door', 'double', 'dragon', 'drapes',
  'draw', 'dream', 'dress', 'drift', 'drill', 'drink', 'drive', 'drop', 'drum', 'dry',
  'duck', 'dumb', 'dune', 'during', 'dust', 'dutch', 'dwarf', 'dynamics', 'eager', 'eagle',
  'early', 'earn', 'earth', 'easily', 'east', 'easy', 'echo', 'ecology', 'economy', 'edge',
  'edit', 'educate', 'educator', 'effort', 'egg', 'eight', 'elbow', 'elder', 'electric', 'elegant',
  'element', 'elephant', 'elevator', 'elite', 'else', 'email', 'embark', 'embody', 'embrace', 'emerge',
  'emotion', 'employ', 'empower', 'empty', 'enable', 'enact', 'end', 'endless', 'endorse', 'enemy',
  'energy', 'enforce', 'engage', 'engine', 'enhance', 'enjoy', 'enlist', 'enough', 'enrich', 'enroll',
  'ensure', 'enter', 'entire', 'entry', 'envelope', 'episode', 'equal', 'equip', 'era', 'erase',
  'error', 'erupt', 'escape', 'essay', 'essence', 'estate', 'eternal', 'ethics', 'evidence', 'evil',
  'evoke', 'evolve', 'exact', 'example', 'excess', 'excite', 'exclude', 'excuse', 'exercise', 'exhaust',
  'exhibit', 'exile', 'exist', 'exit', 'exotic', 'expand', 'expect', 'expire', 'explain', 'expose',
  'express', 'extend', 'extra', 'eye', 'fabric', 'face', 'faculty', 'fade', 'faint', 'faith',
  'fall', 'false', 'fame', 'family', 'famous', 'fan', 'fancy', 'fantasy', 'farm', 'fashion',
  'fat', 'fatal', 'father', 'fatigue', 'fault', 'favor', 'favorite', 'feature', 'february', 'federal',
  'feedback', 'feel', 'female', 'fence', 'festival', 'fever', 'fiber', 'field', 'fiction', 'figure',
  'file', 'film', 'filter', 'final', 'find', 'fine', 'finger', 'finish', 'fire', 'firm',
  'fiscal', 'fish', 'fitness', 'fix', 'flag', 'flame', 'flash', 'flat', 'flavor', 'flee',
  'flesh', 'flight', 'flip', 'float', 'flock', 'flood', 'floor', 'flour', 'flower', 'fluid',
  'flush', 'fly', 'foam', 'focus', 'fog', 'foil', 'fold', 'follow', 'food', 'foot',
  'force', 'forest', 'forget', 'fork', 'fortune', 'forum', 'forward', 'fossil', 'foster', 'found',
  'fox', 'fragile', 'frame', 'frequent', 'fresh', 'friend', 'fringe', 'frog', 'front', 'frost',
  'fruit', 'fuel', 'full', 'fun', 'function', 'funny', 'furnace', 'future', 'gadget', 'gain',
  'galaxy', 'gallery', 'garage', 'garbage', 'garden', 'garlic', 'gas', 'gate', 'gather', 'gauge',
  'gaze', 'general', 'genius', 'genre', 'gentle', 'genuine', 'gesture', 'ghost', 'giant', 'gift',
  'give', 'glad', 'glance', 'glare', 'glass', 'glory', 'glove', 'glow', 'glue', 'goal',
  'gold', 'good', 'goose', 'gorilla', 'gospel', 'gossip', 'govern', 'grab', 'grace', 'grain',
  'grape', 'grant', 'grass', 'gratitude', 'grave', 'great', 'green', 'greet', 'grief', 'grill',
  'grind', 'grip', 'grocery', 'ground', 'group', 'grow', 'growth', 'guitar', 'gun', 'gym',
  'habit', 'hair', 'half', 'hammer', 'hamster', 'hand', 'hang', 'happiness', 'harbor', 'hard',
  'harsh', 'harvest', 'hat', 'hawk', 'hazard', 'head', 'health', 'heart', 'heaven', 'heavy',
  'hedge', 'height', 'hello', 'helmet', 'help', 'hen', 'hero', 'hidden', 'high', 'hill',
  'hint', 'hip', 'hire', 'history', 'hobby', 'hockey', 'hold', 'hole', 'holiday', 'hollow',
  'home', 'honey', 'hood', 'hope', 'horn', 'horror', 'horse', 'hospital', 'host', 'hotel',
  'hour', 'hover', 'hub', 'huge', 'human', 'humble', 'humor', 'hunt', 'hurdle', 'hurry',
  'hurt', 'husband', 'hybrid', 'ice', 'icon', 'idea', 'identify', 'idle', 'ignore', 'ill',
  'illness', 'image', 'imitate', 'immune', 'impact', 'implement', 'imply', 'import', 'impose', 'improve',
  'impulse', 'inch', 'include', 'income', 'increase', 'index', 'indicate', 'indoor', 'industry', 'infant',
  'inflict', 'inform', 'inherit', 'initial', 'inject', 'injury', 'injury', 'inner', 'innocent', 'input',
  'inquiry', 'insect', 'inside', 'inspect', 'inspire', 'install', 'intact', 'interest', 'invest', 'invite',
  'involve', 'iron', 'island', 'isolate', 'issue', 'item', 'ivory', 'jacket', 'jaguar', 'jar',
  'jazz', 'jealous', 'jeans', 'jelly', 'jewel', 'job', 'join', 'joke', 'journey', 'joy',
  'judge', 'juice', 'jump', 'jungle', 'junior', 'junk', 'just', 'kangaroo', 'keen', 'keep',
  'ketchup', 'key', 'kick', 'kid', 'kidney', 'kind', 'kingdom', 'kiss', 'kit', 'kitchen',
  'kite', 'kitten', 'kiwi', 'knee', 'knife', 'knock', 'know', 'koala', 'lab', 'label',
  'labor', 'ladder', 'lady', 'lake', 'lamp', 'language', 'laptop', 'large', 'later', 'latin',
  'laugh', 'laundry', 'lava', 'law', 'lawn', 'lawsuit', 'lawyer', 'layer', 'lazy', 'leader',
  'leaf', 'learn', 'leave', 'lecture', 'left', 'leg', 'legal', 'legend', 'leisure', 'lemon',
  'lend', 'length', 'lens', 'leopard', 'lesson', 'letter', 'level', 'liar', 'liberty', 'library',
  'license', 'life', 'lift', 'light', 'like', 'limb', 'limit', 'link', 'lion', 'liquid',
  'list', 'little', 'live', 'lizard', 'load', 'loan', 'lobster', 'local', 'lock', 'logic',
  'lonely', 'long', 'loop', 'lottery', 'lounge', 'love', 'loyal', 'lucky', 'luggage', 'lumber',
  'lunar', 'lunch', 'luxury', 'lyrics', 'machine', 'mad', 'magic', 'magnet', 'maid', 'mail',
  'main', 'major', 'make', 'mammal', 'man', 'manage', 'mandate', 'mango', 'mansion', 'manual',
  'maple', 'marble', 'march', 'margin', 'marine', 'market', 'marriage', 'mask', 'mass', 'master',
  'mat', 'match', 'material', 'math', 'matrix', 'matter', 'maximum', 'maze', 'meadow', 'mean',
  'measure', 'meat', 'mechanic', 'media', 'melody', 'melt', 'member', 'memory', 'mental', 'mention',
  'menu', 'mercy', 'merge', 'merit', 'merry', 'mesh', 'message', 'metal', 'method', 'middle',
  'midnight', 'milk', 'million', 'mimic', 'mind', 'minimum', 'minor', 'mint', 'minus', 'minute',
  'miracle', 'mirror', 'miss', 'missile', 'mistake', 'mix', 'mixed', 'mixture', 'mobile', 'model',
  'modify', 'mom', 'moment', 'monitor', 'monkey', 'monster', 'month', 'moon', 'moral', 'mortar',
  'mosque', 'mother', 'motion', 'motor', 'mountain', 'mouse', 'mouth', 'move', 'movie', 'much',
  'muffin', 'mule', 'multiply', 'muscle', 'museum', 'mushroom', 'music', 'must', 'mutual', 'mystery',
  'myth', 'nag', 'naive', 'name', 'napkin', 'narrow', 'nation', 'native', 'natural', 'nature',
  'neck', 'need', 'negative', 'neglect', 'neither', 'nephew', 'nerve', 'nest', 'net', 'network',
  'neutral', 'never', 'news', 'next', 'nice', 'night', 'noble', 'noise', 'nominee', 'noodle',
  'normal', 'north', 'nose', 'notable', 'note', 'nothing', 'notice', 'novel', 'now', 'nuclear',
  'number', 'nun', 'nurse', 'nut', 'oak', 'obey', 'object', 'oblige', 'obscure', 'observe',
  'obstacle', 'obtain', 'obvious', 'occur', 'ocean', 'october', 'odor', 'offer', 'office', 'often',
  'oil', 'okay', 'old', 'olive', 'olive', 'olympic', 'omit', 'once', 'one', 'onion',
  'online', 'only', 'open', 'opera', 'opinion', 'oppose', 'option', 'orange', 'orbit', 'orchard',
  'order', 'ordinary', 'organ', 'orient', 'original', 'originate', 'ostrich', 'other', 'outdoor', 'outer',
  'output', 'outside', 'oval', 'oven', 'over', 'own', 'owner', 'oxygen', 'oyster', 'ozzone',
  'pact', 'paddle', 'page', 'pair', 'palace', 'palm', 'panda', 'panel', 'panic', 'panther',
  'paper', 'parade', 'parent', 'park', 'parrot', 'party', 'pass', 'passion', 'passport', 'past',
  'patch', 'path', 'patient', 'patrol', 'pattern', 'pause', 'pave', 'payment', 'peace', 'peanut',
  'pear', 'peasant', 'pelican', 'pen', 'penalty', 'pencil', 'people', 'pepper', 'perfect', 'permit',
  'person', 'pet', 'phone', 'photo', 'phrase', 'physical', 'piano', 'picnic', 'picture', 'pie',
  'pig', 'pigeon', 'pill', 'pilot', 'pink', 'pioneer', 'pipe', 'pistol', 'pivot', 'pizza',
  'place', 'planet', 'plastic', 'plate', 'play', 'please', 'pledge', 'pluck', 'plug', 'plunge',
  'poem', 'poet', 'point', 'polar', 'pole', 'police', 'policy', 'polish', 'polite', 'political',
  'pond', 'pony', 'pool', 'popular', 'portion', 'position', 'possible', 'post', 'potato', 'pottery',
  'poverty', 'powder', 'power', 'practice', 'praise', 'predict', 'prefer', 'prepare', 'present', 'pretty',
  'prevent', 'price', 'pride', 'primary', 'print', 'priority', 'prison', 'private', 'prize', 'problem',
  'process', 'produce', 'profit', 'program', 'project', 'promise', 'promote', 'proof', 'proper', 'property',
  'prosper', 'protect', 'proud', 'provide', 'public', 'pudding', 'pull', 'pulp', 'pumpkin', 'punch',
  'pupil', 'puppy', 'purchase', 'purity', 'purpose', 'purse', 'push', 'put', 'puzzle', 'pyramid',
  'quality', 'quantum', 'quarter', 'queen', 'question', 'quick', 'quiet', 'quiz', 'quote', 'rabbit',
  'raccoon', 'race', 'radar', 'radio', 'rain', 'raise', 'rally', 'ranch', 'range', 'rapid',
  'rare', 'rate', 'rather', 'raven', 'raw', 'razor', 'reach', 'react', 'ready', 'real',
  'reason', 'rebel', 'rebuild', 'recall', 'receive', 'recipe', 'record', 'recycle', 'reduce', 'reflect',
  'reform', 'refuse', 'region', 'regret', 'regular', 'reject', 'relax', 'release', 'relief', 'reluctant',
  'rely', 'remain', 'remember', 'remind', 'remove', 'render', 'renew', 'rent', 'reopen', 'repair',
  'repeat', 'replace', 'report', 'require', 'rescue', 'resemble', 'resist', 'resource', 'respond', 'rest',
  'result', 'retire', 'retreat', 'return', 'reunion', 'reveal', 'review', 'reward', 'rhythm', 'rib',
  'ribbon', 'rice', 'rich', 'ride', 'ridge', 'rifle', 'right', 'rigid', 'ring', 'riot',
  'ripple', 'risk', 'ritual', 'rival', 'river', 'road', 'roast', 'robot', 'robust', 'rocket',
  'romance', 'roof', 'rookie', 'room', 'rose', 'rotate', 'rough', 'round', 'route', 'royal',
  'rubber', 'rude', 'rugby', 'ruler', 'rumor', 'run', 'rural', 'rush', 'rustic', 'ruthless',
  'saddle', 'sadness', 'safe', 'sail', 'salad', 'salmon', 'salon', 'salt', 'salute', 'same',
  'sample', 'sand', 'satisfy', 'satoshi', 'sauce', 'sausage', 'say', 'scale', 'scan', 'scare',
  'scatter', 'scene', 'scheme', 'school', 'science', 'scissors', 'scorpion', 'scout', 'scrap', 'screen',
  'script', 'scrub', 'sea', 'search', 'season', 'seat', 'secret', 'second', 'section', 'security',
  'seed', 'seek', 'segment', 'select', 'sell', 'seminar', 'senior', 'sense', 'sentence', 'september',
  'sequence', 'series', 'servant', 'serve', 'session', 'settle', 'setup', 'seven', 'shadow', 'shaft',
  'shallow', 'share', 'shed', 'shell', 'shelter', 'shift', 'shine', 'ship', 'shiver', 'shock',
  'shoe', 'shoot', 'shop', 'short', 'shoulder', 'shove', 'shrimp', 'shrug', 'shut', 'shy',
  'sibling', 'sick', 'side', 'siege', 'sight', 'sign', 'silent', 'silk', 'silly', 'silver',
  'similar', 'simple', 'since', 'sing', 'siren', 'sister', 'situate', 'six', 'size', 'skate',
  'sketch', 'ski', 'skill', 'skin', 'skull', 'sky', 'slab', 'slang', 'sleep', 'sleeve',
  'slice', 'slide', 'slight', 'slim', 'slip', 'slope', 'slot', 'slow', 'small', 'smart',
  'smile', 'smoke', 'smooth', 'snack', 'snake', 'snap', 'snow', 'soap', 'soccer', 'social',
  'sock', 'soft', 'solar', 'soldier', 'solid', 'solution', 'solve', 'someone', 'song', 'soon',
  'sorry', 'sort', 'soul', 'sound', 'soup', 'source', 'south', 'space', 'spare', 'spatial',
  'spawn', 'speak', 'special', 'speed', 'spell', 'spend', 'sphere', 'spice', 'spider', 'spike',
  'spin', 'spirit', 'spit', 'spite', 'split', 'spoil', 'sponsor', 'spoon', 'sport', 'spot',
  'spray', 'spread', 'spring', 'spy', 'square', 'squeeze', 'squirrel', 'stable', 'stadium', 'staff',
  'stage', 'stairs', 'stamp', 'stand', 'start', 'state', 'stay', 'steak', 'steel', 'stem',
  'step', 'stereo', 'stick', 'still', 'sting', 'stock', 'stomach', 'stone', 'stool', 'stop',
  'storage', 'store', 'storm', 'story', 'stove', 'strategy', 'street', 'strike', 'string', 'strip',
  'stroke', 'strong', 'structure', 'struggle', 'student', 'stuff', 'stumble', 'style', 'subject', 'submit',
  'subway', 'succeed', 'success', 'such', 'sudden', 'suffer', 'sugar', 'suggest', 'suit', 'summer',
  'sunny', 'sunset', 'super', 'supply', 'support', 'supreme', 'sure', 'surface', 'surgery', 'surplus',
  'surprise', 'surround', 'survey', 'suspect', 'sustain', 'swallow', 'swap', 'swamp', 'swan', 'swarm',
  'swear', 'sweat', 'sweep', 'sweet', 'swift', 'swim', 'swing', 'switch', 'sword', 'symbol',
  'system', 'table', 'tackle', 'tag', 'tail', 'talent', 'talk', 'tank', 'tape', 'target',
  'task', 'taste', 'tattoo', 'taxi', 'teach', 'team', 'tell', 'tennis', 'tent', 'term',
  'test', 'text', 'thank', 'that', 'theme', 'then', 'theory', 'therapy', 'there', 'these',
  'they', 'thick', 'thigh', 'thin', 'thing', 'think', 'third', 'this', 'thorn', 'thorough',
  'those', 'though', 'three', 'thrive', 'throw', 'thumb', 'thunder', 'ticket', 'tide', 'tiger',
  'tilt', 'timber', 'time', 'tiny', 'tip', 'tired', 'title', 'toast', 'tobacco', 'toddler',
  'today', 'toe', 'together', 'toilet', 'token', 'tomato', 'tomorrow', 'tonight', 'tool', 'tooth',
  'top', 'topic', 'torch', 'tornado', 'tortoise', 'toss', 'total', 'tourist', 'toward', 'tower',
  'town', 'toy', 'track', 'trade', 'traffic', 'tragic', 'trail', 'train', 'transfer', 'trap',
  'trash', 'tray', 'treat', 'tree', 'trend', 'trial', 'tribe', 'trick', 'trigger', 'trim',
  'trip', 'trophy', 'trouble', 'truck', 'true', 'truly', 'trumpet', 'trunk', 'trust', 'truth',
  'try', 'tube', 'tumble', 'tuna', 'tunnel', 'turkey', 'turn', 'turtle', 'twelve', 'twenty',
  'twice', 'twin', 'twist', 'type', 'tyrant', 'ugly', 'umbrella', 'unable', 'unaware', 'uncle',
  'uncover', 'under', 'undo', 'unfair', 'unfold', 'unhappy', 'uniform', 'unique', 'unit', 'universe',
  'unknown', 'unlock', 'until', 'unusual', 'unveil', 'update', 'upgrade', 'uphold', 'upon', 'upper',
  'upset', 'urban', 'urge', 'usage', 'use', 'used', 'useful', 'usenet', 'usual', 'vacuum',
  'vague', 'valid', 'valley', 'valve', 'van', 'vanish', 'vapor', 'various', 'vast', 'vault',
  'velvet', 'vendor', 'venture', 'venue', 'verb', 'verify', 'version', 'very', 'vessel', 'veteran',
  'viable', 'vibrant', 'vicious', 'victim', 'video', 'view', 'village', 'vintage', 'violin', 'virtual',
  'virus', 'visa', 'visit', 'visual', 'vital', 'vivid', 'vocal', 'voice', 'void', 'volcano',
  'volume', 'vote', 'voyage', 'wage', 'wagon', 'wait', 'walk', 'wall', 'walnut', 'want',
  'warfare', 'warm', 'warrior', 'wash', 'wasp', 'waste', 'watch', 'water', 'wave', 'way',
  'wealth', 'weapon', 'wear', 'weasel', 'weather', 'web', 'wedding', 'weekend', 'weird', 'west',
  'wet', 'whale', 'what', 'wheat', 'wheel', 'when', 'where', 'whip', 'whisper', 'white',
  'whole', 'who', 'wicked', 'wide', 'wife', 'wild', 'will', 'win', 'window', 'wine',
  'wing', 'wink', 'winner', 'winter', 'wire', 'wisdom', 'wise', 'wish', 'witness', 'wolf',
  'woman', 'wonder', 'wood', 'wool', 'word', 'worry', 'worth', 'would', 'wound', 'wrap',
  'wreck', 'wrestle', 'wrist', 'write', 'wrong', 'yard', 'year', 'yellow', 'you', 'young',
  'youth', 'zebra', 'zero', 'zone', 'zoo',
];

// Subset for a simpler 128-bit mnemonic (12 words)
// Using the first 400 words for simplicity
const SIMPLIFIED_WORDLIST = WORDLIST.slice(0, 400);

export function generateMnemonic(wordCount: number = 12): string {
  const words: string[] = [];
  const randomValues = new Uint32Array(wordCount);

  // Use crypto.getRandomValues for secure random generation
  if (typeof crypto !== 'undefined' && crypto.getRandomValues) {
    crypto.getRandomValues(randomValues);
  } else {
    // Fallback for environments without crypto
    for (let i = 0; i < wordCount; i++) {
      randomValues[i] = Math.floor(Math.random() * 0xFFFFFFFF);
    }
  }

  for (let i = 0; i < wordCount; i++) {
    const index = randomValues[i] % SIMPLIFIED_WORDLIST.length;
    words.push(SIMPLIFIED_WORDLIST[index]);
  }

  return words.join(' ');
}

export function validateMnemonic(mnemonic: string): boolean {
  const words = mnemonic.trim().split(/\s+/);
  return words.length >= 12 && words.every(word => SIMPLIFIED_WORDLIST.includes(word));
}
